import '../styles/main.css';
import '../styles/intl-tel-input.css';
import './audio.js';
import './autoPlayVideos.js';
import './menu.js';
import './modal-block.js';
import './phoneInputs.js';
import './privacy-policy.js';
import './scrollAnimation.js';
